apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1-deployment
  namespace: mynamespace
  labels:
    app: test1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
        - name: test1
          image: mydockerimage007.azurecr.io/saisuryachalasani1999/test1:1.o.2
          ports:
          - containerPort: 5000
      imagePullSecrets: 
      - name: mydoc