apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1-deployment
  labels:
    app: test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
        - name: test1
          image: mydockerimage007.azurecr.io/test1:1.0.2
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
          ports:
          - containerPort: 5000
      imagePullSecrets: 
      - name: mydoc