apiVersion: v1
kind: Service
metadata:
  name: test1
  namespace: mynamespace
spec:
  selector:
    app.kubernetes.io/name: test1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer